# Test

name: Test action
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  release:
    name: Test job
    runs-on: ubuntu-18.04
    steps:
      - name: PING
        run: ping ricardomaia.eti.br-c 5
