# Test

name: Test action
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  release:
    name: Test job
    runs-on: ubuntu-18.04
    steps:
      - name: PING
        run: curl -sf ricardomaia.eti.br >/dev/null && if [ ! $? = 6 ]; then echo "is online"; else echo "is down" exit 1; fi
